apiVersion: apps/v1
kind: Deployment
metadata:
  name: rns
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rns
  template:
    metadata:
      labels:
        app: rns
    spec:
      containers:
      - image: 324898396996.dkr.ecr.ap-southeast-2.amazonaws.com/rns:3.0.0
        name: rns
        ports:
        - containerPort: 8095
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8095
          initialDelaySeconds: 120
          periodSeconds: 60
